### ISSUE TITLE
Astor : Double Process display 

### ISSUE THREAD

**Issue by alainbuteau** [tango-controls/Astor#12]
When a DeviceServer has been started 2 times (which is an abnormal situation) the current 7.2.0 version of ASTOR show it in the host view as shown in the attached image
It would be better to display a least a visual worning in the general view showing all hosts so that the operator can directly see something wrong happens 

![astordoublons](https://user-images.githubusercontent.com/29249165/42290569-60598fea-7fc6-11e8-8b0c-859fd2f68df3.png)

**Comment by alainbuteau** [comment]
Hello Pascal
I realized this issue was not assigned 
Do you think my proposal is a good idea ?
If you implement something , we are ready to test it

**Comment by Pascal-Verdier** [comment]
Hello Alain
This feature is not in Astor but in Starter
Feature added in new Starter release (Starter-7.2)
Regards

**Comment by alainbuteau** [comment]
Pascal
I'm not sure I understand your answer et when was the functionnality delivered
In fact , we already have a detection of "double process" and a warning in ASTOR (in the host view) as shown in the attached image. And our version of Starter is older than the 7.2 
Could you be more precise on the version that implement the feature and in which componnent (ASTOR should also be impacted ?)

**Comment by alainbuteau** [comment]
Ps: In the Release Note I do not find the version implementing this

**Comment by Pascal-Verdier** [comment]
I Alain.
To display a global host status as request, that means the Starter State must be ALARM.
So the new release change the Starter state when a double process is detected.
Astor tree is just a kind of viewer of a set of Starter states.

About ReleaseNote, the file does not exist any more since years.
The release notes are available in CHANGELOG.md (git convention).
Changes are in Starter around line 840-880
Cheers
Pascal
